!c::Send ^c
!x::Send ^x
!v::Send +{Insert}
!s::Send ^s
!a::Send ^a
!z::Send ^z
!y::Send ^y
!t::Send ^t
!n::Send ^n
!f::Send ^f
!d::Send ^d
!l::Send ^l
!space::Send ^{space}
!q::Send !{F4}
!w::Send ^{F4}
!1::Send ^1
!Left::Send {Home}
!Right::Send {End}
Capslock::Ctrl
